authusers/urls.py
from django.urls import path
from .views import connexion,register,deconnexion
app_name = "authusers"

urlpatterns = [
    path('connexion',connexion,name="connexion"),
    path('register',register,name="register"),
    path('deconnexion',deconnexion,name="deconnexion")
]

core/urls.py
from django.urls import path,include
# from . import views
from core.views import (index,list_product_category,product_detail,tag_list,
list_product,ajax_add_review,filter_product,add_to_cart,cart,
delete_item_cart,update_item_cart,checkout,payment_success,payment_failed,
customer_dashboard,order_detail,get_wishlist,wishlist,remove_wishlist,contact)


# from .views import ListProductView
app_name = "core"

urlpatterns = [
    path('',index,name="index"),
    path('categorie-produit/<cid>',list_product_category,name="category-product"),
    path('nos-produits',list_product,name="products"),
    path('detail-produit/<pid>/<str:slug>',product_detail,name="detail-product"),
    path('produits/tag/<str:slug_tag>',tag_list,name="tags"),
    path('detail-produit/ajouter-commentaire/<pid>/<str:slug>',ajax_add_review,name="add-review"), 
    path('filter-products/',filter_product,name="filter-product"),
    path('ajouter-au-panier/', add_to_cart , name="add-to-cart"),
    path('mon-panier/',cart,name="cart"),
    path('supprimer-produit-du-panier/', delete_item_cart,name="delete-cart"),
    path('modifier-produit-du-panier/', update_item_cart,name="update-cart"),
    path('checkout-cart/',checkout,name="checkout"),
    path('payment-completed/',payment_success,name="payment-success"),
    path('payment-failed/',payment_failed,name="payment-failed"),
    path('paypal/',include('paypal.standard.ipn.urls')), 
    path('tableau-de-bord/',customer_dashboard,name="dashboard"),
    path('tableau-de-bord/detail-order/<int:id>',order_detail,name="order-detail"),
    path('wishlist/',wishlist,name="wishlist"),
    path('ajouter-wishlist/',get_wishlist,name='add-wishlist'),
    path('supprimer-wishlist/',remove_wishlist,name='remove-wishlist'),
    path('contactez-nous/',contact,name="contact")




    # path('nos_produits',views.ListProductView.as_view , name="products")
]

pmagasin/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import  settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('users/',include('authusers.urls')), 
    path('ckeditor/',include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from .models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Laissez un commentaire','id':'text-review'}))

    class Meta:
        model = ProductReview
        fields = ['review','rating']

core/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render , redirect, get_object_or_404
from .models import Category,Product,ProductReview,CartOrder,CartOrderItems,Wishlist,Address
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from taggit.models import Tag

from .forms import ProductReviewForm
from django.http import JsonResponse,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.template.loader import render_to_string
from django.contrib import messages

from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls import reverse
from authusers.models import Profile,ContactUs
from django.core import serializers
from django.db.models import Avg,Count,Q
import calendar
from django.db.models.functions import ExtractMonth
# from core.filters import ProductFilter
# from django.views.generic.list import ListView

# Create your views here.
def index(request):
    categories =Category.objects.all()
    products  = Product.objects.all().order_by('-date')[:8]
    search = request.GET.get('recherche')
    if search != '' and search is not None:
        products = Product.objects.filter(
            Q(title__icontains = search ) and Q(category__title__icontains=search)
            )
    # paginator = Paginator(products,4)
    # page =request.GET.get('page')
    # try:
    #     products = paginator.page(page)
    # except PageNotAnInteger:
    #     products = paginator.page(1)
    # except EmptyPage:
    #     products = paginator.page(paginator.num_pages)
    context={
        'categories':categories,
        'products':products
    }

    return render(request,'core/index.html',context)


# class ListProductView(ListView):
#     queryset = Product.objects.all()
#     template_name = "products2.html"
#     context_object_name ="products"

#     def get_queryset(self):
#         queryset= super().get_queryset()
#         self.filterset =ProductFilter(self.request.GET , queryset=queryset)
#         return self.filterset.qs

#     def get_context_data(self, **kwargs: Any):
#         context =  super().get_context_data(**kwargs)
#         context['form'] = self.filterset.form
#         return context


def is_valid_query(param):
    return param !=''and param is not None

def list_product(request):
    query = Product.objects.all().order_by("-date")
    # product_filter=ProductFilter(request.GET , queryset=query) 


    category = Category.objects.all()

    search_product_category = request.GET.get('recherche')
    search_price_min = request.GET.get('min')
    search_price_max = request.GET.get('max')

    search_date_debut = request.GET.get('debut')   
    search_date_end = request.GET.get('end')


    if is_valid_query(search_product_category):
        query = query.filter(Q(title__icontains = search_product_category) | Q(category__title__icontains = search_product_category))
    if is_valid_query(search_price_min):
        query = query.filter(price__gte = search_price_min)
    if is_valid_query(search_price_max):
        query =query.filter(price__lt=search_price_max)
    if is_valid_query(search_date_debut):
        query = query.filter(date__gte = search_date_debut)
    if is_valid_query(search_date_end):
        query = query.filter(date__lt=search_date_end)

    paginator = Paginator(query,6)
    page =request.GET.get('page')
    try:
       query = paginator.page(page)
    except PageNotAnInteger:
        query = paginator.page(1)
    except EmptyPage:
        query = paginator.page(paginator.num_pages)
    context = {
        # 'form': product_filter.form,
        'products':query,
        'cat':category
    }
    return render(request , 'core/product.html',context)


def list_product_category(request,cid):
    category = Category.objects.all()
    categories = Category.objects.get(cid=cid)
    product = Product.objects.filter(category=categories)
    paginator = Paginator(product , 3)
    page = request.GET.get('page')
    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)

    context={
        'categories':categories,
        'products':product,
        'cat':category
    }
    return render(request,'core/category_product.html',context)

def product_detail(request,slug,pid):
    products = get_object_or_404(Product,slug=slug,pid=pid)
    image_product = products.p_image.all()
    c_products = Product.objects.filter(category=products.category).exclude(pid=pid)

    reviews = ProductReview.objects.filter(product=products).order_by('-date')

    avg_reviews = ProductReview.objects.filter(product=products).aggregate(rating=Avg('rating'))

    form_review = ProductReviewForm()
    # 

    context ={
        'products':products,
        'image':image_product,
        'cproducts':c_products,
        'reviews':reviews,
        'avg':avg_reviews,
        'form_review':form_review,
    }
    return render(request,'core/product-detail.html',context)

def tag_list(request,slug_tag=None):
    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None
    if slug_tag:
        tag = get_object_or_404(Tag,slug=slug_tag)
        products =products.filter(tags__in=[tag])

    context={
        'products':products,
        'tag':tag
    }
    return render(request,'core/tag.html',context)

def ajax_add_review(request,slug,pid):
    products = Product.objects.get(slug=slug,pid=pid)
    user =request.user
    rev = ProductReview.objects.create(
        user = user , 
        product = products,
        review = request.POST['review'],
        rating = request.POST['rating']
    )
    
    avg_review = ProductReview.objects.filter(product=products).aggregate(rating=Avg('rating'))
    context = {
        'user':user.username,
        'review':request.POST['review'],
        'rating': request.POST['rating']
    }
    return JsonResponse(
        {
            'bool':True,
            'context':context,
            'avg':avg_review,
        }
    )




def filter_product(request):
    categories = request.GET.getlist('category[]')
    products = Product.objects.all().order_by('-id').distinct()

   
    # min_price = request.GET['min_price']
    # max_price = request.GET['max_price']

    # products = products.filter(price__gte=min_price)
    # products = products.filter(price__lt=max_price)



    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    paginator = Paginator(products,6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    data = render_to_string("core/async/product.html", {"products":products})
    return JsonResponse(
        {
            'data':data
        }
    )
     

def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'quantity':request.GET['quantity'],
        'price':request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid']
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET["id"])]['quantity'] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse(
        {
            "data":request.session['cart_data_obj'],
            'totalitems': len(request.session['cart_data_obj'])
        }
    )


def cart(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])
        return render(request,'core/cart.html',{
             'cart_data':request.session['cart_data_obj'],
             'totalitems': len(request.session['cart_data_obj']),
             'cart_total_amount': cart_total_amount
            })
    else:
        messages.warning(request,"Votre panier est vide")
        return redirect('core:index')

def delete_item_cart(request):
    product_id =str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
             
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html",{
        'cart_data':request.session['cart_data_obj'],
        'cart_total_amount': cart_total_amount
    })
    return JsonResponse({
        'data':context,
        'totalitems': len(request.session['cart_data_obj']),
    })
            

def update_item_cart(request):
    product_id =str(request.GET['id'])
    product_qty = request.GET['quantity']
    

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fashion</title>
    <link rel="shortcut icon" type="image" href="/static/assets/image/logo2.png">
    
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- bootstrap links -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
   
    <!-- bootstrap links -->

    <!-- fonts links -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- fonts links -->

    <!-- static links -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}"> 
    
    
    <!-- <link rel="stylesheet" href="{% static 'assets/css/font-awesome-6.2.0-all.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}"> 
    <!-- static links -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" />

    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/dashboard.js' %}"></script>
    <style>
      .separator{
              border-top: 1px solid #333;
              margin: 35px 0;
          }
    .card-img-top{
        width: 100%;
        height: 300px;
        object-fit: cover;
    }
    </style>
</head>
<body>
  <!-- background: #1c1c50; #0d6efd;-->
    <!-- top navbar -->
    <div class="top-navbar">
        <div class="top-icons">
            <i class="fa-brands fa-twitter"></i>
            <i class="fa-brands fa-facebook-f"></i>
            <i class="fa-brands fa-instagram"></i>
        </div>
        <div class="other-links">
            <div class="other-links">
              <a href="{% url 'core:dashboard' %}"><i class="fa-solid fa-user"></i></a>
              <a href="{% url 'core:cart' %}"><i class="fa-solid fa-cart-shopping"><span style="top: -5px; left: 15px; height: 20px; min-width: 20px;" id="cart-items-count" class="justify-content-center border border-primary text-items-center rounded-circle px-1 m-1 bg-primary text-light">{{ request.session.cart_data_obj|length }}</span></i></a>
              <a href="{% url 'core:wishlist' %}" class="text-decoration-none"><i class="fa-solid fa-heart"><span style="top: -5px; left: 15px; height: 20px; min-width: 20px;"  class="justify-content-center border border-primary text-items-center rounded-circle px-1 m-1 bg-primary text-light">{{ wishlist.count }}</span></i></a>
              
          </div> 
        </div>
    </div>
    <!-- top navbar -->

    <div class="home-section">
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg" id="navbar">
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><img src="{% static './image/logo.png' %}" alt="" width="180px"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span><i class="fa-solid fa-bars" style="color: white;"></i></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Accueil</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:products' %}">Nos Produits</a>
                  </li>
                  <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Categories
                    </a>
                    
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #1c1c50;">
                      
                      <li><a class="dropdown-item" href="#">T-Shirts</a></li>
                      <li><a class="dropdown-item" href="#">Sweats à capuche</a></li>
                      <li><a class="dropdown-item" href="#">Pantalons</a></li>
                      <li><a class="dropdown-item" href="#">Chaussures</a></li>
                      <li><a class="dropdown-item" href="#">Montres</a></li>
                      <li><a class="dropdown-item" href="#">Lunettes</a></li>
                    </ul>
                  </li> -->
                  <li class="nav-item">
                    <a class="nav-link" href="about.html">A propos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:contact' %}">Contactez nous</a>
                  </li>
                </ul>
               
                <!-- <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Recherche" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit" id="search-btn">Recherche</button>
                </form> -->
                <div class="d-flex">
                  
                  <button id="btn-login"><a href="">S'enregister</a></button>
                  <button id="btn-signup"><a href="">Connexion</a></button>
                </div>
                
           
              </div>
            </div>
          </nav>
          
          <!-- <section class="home">
            <div class="content">
                <h3>Les produits 
                    <br> <span>100% de qualité</span>
                </h3>
                <p>Les produits que vous désirez à moindre coût!</p>
            </div>
            <div class="img">
                <img src="{% static '/static/assets/image/b2.png' %}" alt="">
            </div>
        </section> -->
    </div>
        <!-- navbar -->

{% if messages %}
{% for message in messages%}
<div class="alert alert-{{message.tags}}">
    <strong>{{ message }}</strong>
</div>

{% endfor %}
{% endif %}
<script>
setTimeout(()=>{
    $(".alert").alert("close")
},3000)
</script>
{% block content %}


{% endblock %}
 


<!-- footer -->
<footer id="footer" style="margin-top: 40px;">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 footer-content">
                    <h3>Fashion</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, hic?</p>
                    <p>
                        Karcahi <br>
                        Sindh <br>
                        Pakistan <br>
                    </p>
                    <strong><i class="fas fa-phone"></i> Phone: <strong>+000000000000000</strong></strong><br>
                    <strong><i class="fa-solid fa-envelope"></i> Email: <strong>example@gmail.com</strong></strong>
                </div>
                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Usefull Links</h4>
                    <ul>
                      <li><a href="">Accueil</a></li>
                      <li><a href="">A propos</a></li>
                      <li><a href="">Contacts</a></li>
                      <li><a href="#">Services</a></li>
    
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Nos Services</h4>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Modi, rem!</p>
                    <ul>
                        <li><a href="#">Smartphones</a></li>
                        <li><a href="#">Montres intelligentes</a></li>
                        <li><a href="#">Airpods</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Nos reseaux sociaux</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, ad?</p>
                    <div class="socail-links mt-3">
                        <!-- <a href="#" class="twiiter"><i class="fa-brands fa-twitter"></i></a> -->
                        <a href="#" class="twiiter"><i class="fa-brands fa-facebook-f"></i></a>
                        <!-- <a href="#" class="twiiter"><i class="fa-brands fa-google-plus"></i></a> -->
                        <a href="#" class="twiiter"><i class="fa-brands fa-instagram"></i></a>
                        <a href="#" class="twiiter"><i class="fa-brands fa-tiktok"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container py-4">
        <div class="copyright">
            &copy; Copyright <strong>Fashion</strong>.All Rights Reserved
        </div>
        <div class="credits">
            Designed By <a href="#"></a>
        </div>
    </div>
    </footer>
    <!-- footer -->
    
    <a href="#" class="arrow"><i><img src="{% static './image/up-arrow.png' %}" alt="" width="50px"></i></a>
    
        
        <script src="{% static 'assets/js/script.js' %}"></script>
        
       
        <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        
        <script type="text/javaScript">
          var swiper = new Swiper(".swiper_thumb", {
        spaceBetween: 10,
        slidesPerView: 4,
        speed: 300,
        loop: true,
        freeMode: true,
        watchSlidesProgress: true,
        ClickAble: true,
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
      });
      var swiper2 = new Swiper(".swiper_large_preview", {
        spaceBetween: 10,
        slidesPerView: 1,
        // speed: 300,
        speed: 0,
        loop: true,
        // freeMode: true,
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
        thumbs: {
          swiper: swiper,
        },
      });
      </script>
    </body>
    </html>

templates/core/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'assets/css/cart.css' %}">
</head>
<div class="container-fluid mb-3">
    <div class="row">
      <div class="col-md-12 bg-light border-bottom pt-5 pb-5">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h2>Panier</h2>
              <ol class="breadcrumb p-0 m-0 bg-transparent">
                <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Accueil</a></li>
                <li class="breadcrumb-item active">Panier</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="container-fluid" id="cart-list">
    <div class="row">
        <aside class="col-lg-9">
             <p class="text-muted small fs-5">Vous avez <span class="text-danger fw-bolder">{{totalitems}} produit{{totalitems|pluralize}}</span> dans votre panier</p>
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted bg-primary">
                            <tr class="small text-uppercase text-light">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" width="120">Subtotal</th>
                                <th scope="col" class="text-right d-none d-md-block" width="200"></th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for product_id,item in cart_data.items %}
                            <tr>

                                <td>
                                    <p class="info"> <a href="#" class="title-xs text-dark " data-abc="true">{{item.title}}</a>
                                       
                                    </p>
                                    <div class="itemside align-items-center">
                                        <div class="aside"><img src="{{item.image}}" class="img-sm"></div>
                                       
                                    </div>

                                   
                                </td>
                                <td> 
                                    <input type="number" class="form-control product-quantity-{{product_id}}" value="{{item.quantity}}">
                                </td>
                                <td>
                                    <div class="price-wrap"> <var class="price ">{{item.price}} fcfa</var>  </div> 
                                    <!-- <small class="text-muted"> $9.20 each </small> -->
                                </td>
                                <td>
                                    <div class="price-wrap"> <var class="price">{% widthratio item.price 1 item.quantity %} fcfa </var>  </div> 
                                    <!-- <small class="text-muted"> $9.20 each </small> -->
                                </td>
                                <td class="text-right d-none d-md-block">
                                     <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip" data-abc="true"><i class="fa fa-heart"></i></a>
                                    <button type="button" class="btn btn-light edit-product" data-product="{{product_id}}"><i class="fas fa-edit"></i></button> 
                                    <button type="button" class="btn btn-light remove-product" data-product="{{product_id}}" > Supprimer</button>
                                </td>
                            </tr>
                           {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </aside>
        <aside class="col-lg-3">
            <div class="card mb-3">
                <div class="card-body">
                    <form>
                        <div class="form-group"> <label>Have coupon?</label>
                            <div class="input-group"> <input type="text" class="form-control coupon" name="" placeholder="Coupon code"> <span class="input-group-append"> <button class="btn btn-primary btn-apply coupon">Apply</button> </span> </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                        <dt>Total Subtotal:</dt>
                        <dd class="text-right ml-3">{{cart_total_amount|floatformat:0}} fcfa</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Discount:</dt>
                        <dd class="text-right text-danger ml-3">- $10.00</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Total de l'achat:</dt>
                        <dd class="text-right text-dark b ml-3"><strong>{{cart_total_amount|floatformat:0}}  fcfa</strong></dd>
                    </dl>
                    <hr> 
                    {% if totalitems %}
                    <a href="{% url 'core:checkout' %}" class="btn btn-out btn-primary btn-square btn-main" data-abc="true"> Make Checkout </a>
                    {% endif %}
                     <a href="{% url 'core:products' %}" class="btn btn-out btn-success btn-square btn-main mt-2" data-abc="true">Continue Shopping</a>
                </div>
            </div>
        </aside>
    </div>
</div>

{% endblock %}

templates/core/payment-failed.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container-fluid py-5 position-relative bg-light">
    <h1 class="text-center text-primary display-6">Paiement echoué</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Accueil</a></li>
        <li class="breadcrumb-item active text-primary">Paiement echoué</li>
    </ol>
</div>
<div class="container-fluid">
    <div class="container  text-center">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <i class="fa-solid fa-x fa-2xl display-1 text-danger "></i>
                <i class="bi bi-exclamation-triangle display-1 text-secondary"></i>
                <h1 class="display-1">Erreur 404</h1>
                <h1 class="mb-4">Page introuvable</h1>
                <p class="mb-4">Paiement echoué </p>
                <a class="btn border-secondary rounded-pill py-3 px-5" href="{% url 'core:index' %}">Go Back To Home</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}