core/urls.py
from django.urls import path,include
# from . import views
from core.views import (index,list_product_category,product_detail,tag_list,
list_product,ajax_add_review,filter_product,add_to_cart,cart,
delete_item_cart,update_item_cart,checkout,payment_success,payment_failed,
customer_dashboard,order_detail,get_wishlist,wishlist,remove_wishlist,contact)


# from .views import ListProductView
app_name = "core"

urlpatterns = [
    path('',index,name="index"),
    path('categorie-produit/<cid>',list_product_category,name="category-product"),
    path('nos-produits',list_product,name="products"),
    path('detail-produit/<pid>/<str:slug>',product_detail,name="detail-product"),
    path('produits/tag/<str:slug_tag>',tag_list,name="tags"),
    path('detail-produit/ajouter-commentaire/<pid>/<str:slug>',ajax_add_review,name="add-review"), 
    path('filter-products/',filter_product,name="filter-product"),
    path('ajouter-au-panier/', add_to_cart , name="add-to-cart"),
    path('mon-panier/',cart,name="cart"),
    path('supprimer-produit-du-panier/', delete_item_cart,name="delete-cart"),
    path('modifier-produit-du-panier/', update_item_cart,name="update-cart"),
    path('checkout-cart/',checkout,name="checkout"),
    path('payment-completed/',payment_success,name="payment-success"),
    path('payment-failed/',payment_failed,name="payment-failed"),
    path('paypal/',include('paypal.standard.ipn.urls')), 
    path('tableau-de-bord/',customer_dashboard,name="dashboard"),
    path('tableau-de-bord/detail-order/<int:id>',order_detail,name="order-detail"),
    path('wishlist/',wishlist,name="wishlist"),
    path('ajouter-wishlist/',get_wishlist,name='add-wishlist'),
    path('supprimer-wishlist/',remove_wishlist,name='remove-wishlist'),
    path('contactez-nous/',contact,name="contact")




    # path('nos_produits',views.ListProductView.as_view , name="products")
]

pmagasin/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import  settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('users/',include('authusers.urls')), 
    path('ckeditor/',include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from .models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Laissez un commentaire','id':'text-review'}))

    class Meta:
        model = ProductReview
        fields = ['review','rating']

core/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render , redirect, get_object_or_404
from .models import Category,Product,ProductReview,CartOrder,CartOrderItems,Wishlist,Address
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from taggit.models import Tag

from .forms import ProductReviewForm
from django.http import JsonResponse,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.template.loader import render_to_string
from django.contrib import messages

from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls import reverse
from authusers.models import Profile,ContactUs
from django.core import serializers
from django.db.models import Avg,Count,Q
import calendar
from django.db.models.functions import ExtractMonth
# from core.filters import ProductFilter
# from django.views.generic.list import ListView

# Create your views here.
def index(request):
    categories =Category.objects.all()
    products  = Product.objects.all().order_by('-date')[:8]
    search = request.GET.get('recherche')
    if search != '' and search is not None:
        products = Product.objects.filter(
            Q(title__icontains = search ) and Q(category__title__icontains=search)
            )
    # paginator = Paginator(products,4)
    # page =request.GET.get('page')
    # try:
    #     products = paginator.page(page)
    # except PageNotAnInteger:
    #     products = paginator.page(1)
    # except EmptyPage:
    #     products = paginator.page(paginator.num_pages)
    context={
        'categories':categories,
        'products':products
    }

    return render(request,'core/index.html',context)


# class ListProductView(ListView):
#     queryset = Product.objects.all()
#     template_name = "products2.html"
#     context_object_name ="products"

#     def get_queryset(self):
#         queryset= super().get_queryset()
#         self.filterset =ProductFilter(self.request.GET , queryset=queryset)
#         return self.filterset.qs

#     def get_context_data(self, **kwargs: Any):
#         context =  super().get_context_data(**kwargs)
#         context['form'] = self.filterset.form
#         return context


def is_valid_query(param):
    return param !=''and param is not None

def list_product(request):
    query = Product.objects.all().order_by("-date")
    # product_filter=ProductFilter(request.GET , queryset=query) 


    category = Category.objects.all()

    search_product_category = request.GET.get('recherche')
    search_price_min = request.GET.get('min')
    search_price_max = request.GET.get('max')

    search_date_debut = request.GET.get('debut')   
    search_date_end = request.GET.get('end')


    if is_valid_query(search_product_category):
        query = query.filter(Q(title__icontains = search_product_category) | Q(category__title__icontains = search_product_category))
    if is_valid_query(search_price_min):
        query = query.filter(price__gte = search_price_min)
    if is_valid_query(search_price_max):
        query =query.filter(price__lt=search_price_max)
    if is_valid_query(search_date_debut):
        query = query.filter(date__gte = search_date_debut)
    if is_valid_query(search_date_end):
        query = query.filter(date__lt=search_date_end)

    paginator = Paginator(query,6)
    page =request.GET.get('page')
    try:
       query = paginator.page(page)
    except PageNotAnInteger:
        query = paginator.page(1)
    except EmptyPage:
        query = paginator.page(paginator.num_pages)
    context = {
        # 'form': product_filter.form,
        'products':query,
        'cat':category
    }
    return render(request , 'core/product.html',context)


def list_product_category(request,cid):
    category = Category.objects.all()
    categories = Category.objects.get(cid=cid)
    product = Product.objects.filter(category=categories)
    paginator = Paginator(product , 3)
    page = request.GET.get('page')
    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)

    context={
        'categories':categories,
        'products':product,
        'cat':category
    }
    return render(request,'core/category_product.html',context)

def product_detail(request,slug,pid):
    products = get_object_or_404(Product,slug=slug,pid=pid)
    image_product = products.p_image.all()
    c_products = Product.objects.filter(category=products.category).exclude(pid=pid)

    reviews = ProductReview.objects.filter(product=products).order_by('-date')

    avg_reviews = ProductReview.objects.filter(product=products).aggregate(rating=Avg('rating'))

    form_review = ProductReviewForm()
    # 

    context ={
        'products':products,
        'image':image_product,
        'cproducts':c_products,
        'reviews':reviews,
        'avg':avg_reviews,
        'form_review':form_review,
    }
    return render(request,'core/product-detail.html',context)

def tag_list(request,slug_tag=None):
    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None
    if slug_tag:
        tag = get_object_or_404(Tag,slug=slug_tag)
        products =products.filter(tags__in=[tag])

    context={
        'products':products,
        'tag':tag
    }
    return render(request,'core/tag.html',context)

def ajax_add_review(request,slug,pid):
    products = Product.objects.get(slug=slug,pid=pid)
    user =request.user
    rev = ProductReview.objects.create(
        user = user , 
        product = products,
        review = request.POST['review'],
        rating = request.POST['rating']
    )
    
    avg_review = ProductReview.objects.filter(product=products).aggregate(rating=Avg('rating'))
    context = {
        'user':user.username,
        'review':request.POST['review'],
        'rating': request.POST['rating']
    }
    return JsonResponse(
        {
            'bool':True,
            'context':context,
            'avg':avg_review,
        }
    )




def filter_product(request):
    categories = request.GET.getlist('category[]')
    products = Product.objects.all().order_by('-id').distinct()

   
    # min_price = request.GET['min_price']
    # max_price = request.GET['max_price']

    # products = products.filter(price__gte=min_price)
    # products = products.filter(price__lt=max_price)



    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    paginator = Paginator(products,6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    data = render_to_string("core/async/product.html", {"products":products})
    return JsonResponse(
        {
            'data':data
        }
    )
     

def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'quantity':request.GET['quantity'],
        'price':request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid']
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET["id"])]['quantity'] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse(
        {
            "data":request.session['cart_data_obj'],
            'totalitems': len(request.session['cart_data_obj'])
        }
    )


def cart(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])
        return render(request,'core/cart.html',{
             'cart_data':request.session['cart_data_obj'],
             'totalitems': len(request.session['cart_data_obj']),
             'cart_total_amount': cart_total_amount
            })
    else:
        messages.warning(request,"Votre panier est vide")
        return redirect('core:index')

def delete_item_cart(request):
    product_id =str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
             
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html",{
        'cart_data':request.session['cart_data_obj'],
        'cart_total_amount': cart_total_amount
    })
    return JsonResponse({
        'data':context,
        'totalitems': len(request.session['cart_data_obj']),
    })
            

def update_item_cart(request):
    product_id =str(request.GET['id'])
    product_qty = request.GET['quantity']
    

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']

templates/core/async/cart-list.html
<div class="container-fluid" id="cart-list">
    <div class="row">
        <aside class="col-lg-9">
             <p class="text-muted small fs-5">Vous avez <span class="text-danger fw-bolder">{{totalitems}} produit{{totalitems|pluralize}}</span> dans votre panier</p>
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted bg-primary">
                            <tr class="small text-uppercase text-light">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" width="120">Subtotal</th>
                                <th scope="col" class="text-right d-none d-md-block" width="200"></th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for product_id,item in cart_data.items %}
                            <tr>

                                <td>
                                    <p class="info"> <a href="#" class="title-xs text-dark " data-abc="true">{{item.title}}</a>
                                       
                                    </p>
                                    <div class="itemside align-items-center">
                                        <div class="aside"><img src="{{item.image}}" class="img-sm"></div>
                                       
                                    </div>

                                   
                                </td>
                                <td> 
                                    <input type="number" class="form-control product-quantity-{{product_id}}" value="{{item.quantity}}">
                                </td>
                                <td>
                                    <div class="price-wrap"> <var class="price">{{item.price}} fcfa</var>  </div> 
                                    <!-- <small class="text-muted"> $9.20 each </small> -->
                                </td>
                                <td>
                                    <div class="price-wrap"> <var class="price">{% widthratio item.price 1 item.quantity %} fcfa </var>  </div> 
                                    <!-- <small class="text-muted"> $9.20 each </small> -->
                                </td>
                                <td class="text-right d-none d-md-block">
                                     <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip" data-abc="true"><i class="fa fa-heart"></i></a>
                                     <button type="button" class="btn btn-light edit-product" data-product="{{product_id}}"><i class="fas fa-edit"></i></button> 
                                    <button type="button" class="btn btn-light remove-product" data-product="{{product_id}}" > Supprimer</button>
                                </td>
                            </tr>
                           {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </aside>
        <aside class="col-lg-3">
            <div class="card mb-3">
                <div class="card-body">
                    <form>
                        <div class="form-group"> <label>Have coupon?</label>
                            <div class="input-group"> <input type="text" class="form-control coupon" name="" placeholder="Coupon code"> <span class="input-group-append"> <button class="btn btn-primary btn-apply coupon">Apply</button> </span> </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                        <dt>Total Subtotal:</dt>
                        <dd class="text-right ml-3">{{cart_total_amount|floatformat:0}} fcfa</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Discount:</dt>
                        <dd class="text-right text-danger ml-3">- $10.00</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Total de l'achat:</dt>
                        <dd class="text-right text-dark b ml-3"><strong>{{cart_total_amount|floatformat:0}}  fcfa</strong></dd>
                    </dl>
                    <!-- <hr> <a href="{% url 'core:checkout' %}" class="btn btn-out btn-primary btn-square btn-main" data-abc="true"> Make Purchase </a> <a href="#" class="btn btn-out btn-success btn-square btn-main mt-2" data-abc="true">Continue Shopping</a> -->
                    {% if totalitems %}
                    <a href="{% url 'core:checkout' %}" class="btn btn-out btn-primary btn-square btn-main" data-abc="true"> Make Checkout </a>
                    {% endif %}
                     <a href="{% url 'core:products' %}" class="btn btn-out btn-success btn-square btn-main mt-2" data-abc="true">Continue Shopping</a>
                </div>
            </div>
        </aside>
    </div>
</div>

templates/core/async/product.html
{% if products %}
       
        <div class="card-body">
          <div class="row" id="filtered-product">
          {% for product in products %}
            <div class="col-md-4 mb-4">
              <div class="card">
                <img class="card-img-top" src="{{ product.image.url }}"  alt="" />
                <div class="card-body">
                  <p class="h6"><small class="text-muted"></small></br>{{product.title}}</p>
                  <p class="m-0 text-muted">{{product.category.title}}</p>
                  <p class="m-0">
                    <i class="fa-xs far fa-star"></i>
                    <i class="fa-xs far fa-star"></i>
                    <i class="fa-xs far fa-star"></i>
                    <i class="fa-xs far fa-star"></i>
                    <i class="fa-xs far fa-star"></i>
                  </p>
                  <p class="h5 m-0">{{product.price}} Fcfa</p>
                </div>
                <div class="card-footer p-0">
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-light">
                      <i class="fas fa-cart-plus"></i>
                      
                    </button>
                    <!-- <button type="button" class="btn btn-light">
                      <i class="fas fa-shopping-cart"></i>
                    </button>
                    <button type="button" class="btn btn-light">
                      <i class="fas fa-heart"></i>
                    </button> -->
                    <button type="button" class="btn btn-light">
                      <a class="text-decoration-none text-capitalize"   href="{% url 'core:detail-product' slug=product.slug pid=product.pid %}">details</a>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="card-footer p-3">
          <div class="row">
            <div class="col-md-6">
              <ul class="pagination m-0">
                  {% if products.has_previous %}
                <li class="page-item "> 
                  <a href="?page={{products.previous_page_number}}" class="page-link text-decoration-none text-uppercase">Précédent</a>
                </li>
                {% endif %}

                {% for i in products.paginator.page_range %}
                  {% if products.number == i %}
                  <li class="page-item"><a class="page-link" href="#">{{i}}</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                  {% endif%}
                {% endfor %}

                {% if products.has_next %}
                <li class="page-item">
                  
                  <a href="?page={{products.next_page_number}}" class="page-link text-decoration-none text-uppercase">Suivant</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <br><br><br><br><br><br><br>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>         
  <div style="color: #575757; font-style: bold; font-size: 1.5rem; text-align: center;">Aucun produit correspond à votre recherche...</div>
  {% endif %}
 

 
</div>

templates/core/async/wishlist-list.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'assets/css/wishlist.css' %}">
</head>

<!------ Include the above in your HEAD tag ---------->


	<div class="cart-wrap">
		<div class="container">
	        <div class="row">
			    <div class="col-md-12">
			        <div class="main-heading mb-10">My wishlist</div>
			        <div class="table-wishlist">
				        <table cellpadding="0" cellspacing="0" border="0" width="100%">
				        	<thead>
					        	<tr>
					        		<th width="45%">Product Name</th>
					        		<th width="15%">Unit Price</th>
					        		<th width="15%">Stock Status</th>
					        		<th width="15%"></th>
					        		<th width="10%"></th>
					        	</tr>
					        </thead>
					        <tbody class="tbody-text">
                                {% for w in wishlist %}
					        	<tr>
					        		<td width="45%">
					        			<div class="display-flex align-center">
		                                    <div class="img-product">
		                                        <img src="{{w.product.image.url }}" alt="" class="mCS_img_loaded">
		                                    </div>
                                            <a href="{% url 'core:detail-product' slug=w.product.slug pid=w.product.pid %}"></a>
		                                    <div class="name-product">
		                                       {{w.product.title }}
		                                    </div>
	                                    </div>
	                                </td>
					        		<td width="15%" class="price current-product-price-{{w.product.id}}">{{w.product.price}}</td>
                                    
                                    <td><span>{% if w.product.in_stock %} En stock  {% else %} En rupture de stock {% endif %} </span></td>
                                    
                                    <input type="hidden" class="product-quantity-{{w.product.id}}" value="1"  id="product-quantity">
                                    <input type="hidden" class="product-pid-{{w.product.id}}"    value="{{ w.product.pid }}">
                                    <input type="hidden" class="product-image-{{ w.product.id}}" value="{{ w.product.image.url }}" >
                                    <input type="hidden" class="product-title-{{ w.product.id}}" value="{{ w.product.title }}" >
                                    <input type="hidden" class="product-id-{{ w.product.id}}"    value="{{ w.product.id }}" >

					        		<td width="15%"><button  data-index="{{w.product.id}}" class="round-black-btn small-btn add-to-cart-btn">Add to Cart</button></td>
					        		<td width="10%" class="text-center"><button data-wishlist-product="{{w.id}}" class="trash-icon remove-to-wishlist"><i class="far fa-trash-alt "></i></button></td>
					        	</tr>
                                {% endfor %}
					        	
				        	</tbody>
				        </table>
				    </div>
			    </div>
			</div>
		</div>
	</div>
	